[package]
name = "wroid-cli"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[[bin]]
name = "wroid"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
crossterm.workspace = true
dbus.workspace = true
gtk = { version = "0.18.2", features = ["v3_24"] }
libc.workspace = true
serde.workspace = true
serde_json.workspace = true
wroid-adb = { path = "../wroid-adb" }
wroid-android = { path = "../wroid-android" }
wroid-core = { path = "../wroid-core" }
wroid-daemon = { path = "../wroid-daemon" }
wroid-inject = { path = "../wroid-inject" }
wroid-input = { path = "../wroid-input" }
wroid-runtime = { path = "../wroid-runtime" }
wroid-waydroid = { path = "../wroid-waydroid" }
webkit2gtk = { version = "2.0.2", features = ["v2_40"] }

[dev-dependencies]
tempfile.workspace = true
