[package]
name = "wroid-inject"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
evdev.workspace = true
libc.workspace = true
thiserror.workspace = true
wroid-core = { path = "../wroid-core" }
wroid-input = { path = "../wroid-input" }
wroid-runtime = { path = "../wroid-runtime" }

[[bin]]
name = "wroid-runtime-channel-bench"
path = "src/bin/wroid-runtime-channel-bench.rs"

[dev-dependencies]
tempfile.workspace = true
